package producer

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

type Runner func(name string, args ...string) ([]byte, error)

func ExecRunner(name string, args ...string) ([]byte, error) {
	return exec.Command(name, args...).CombinedOutput()
}

type UserUnit struct {
	Name        string
	Description string
	ExecStart   []string
	Env         map[string]string
}

func NewUserUnit(name, description string, execStart ...string) UserUnit {
	u := UserUnit{Name: name, Description: description, ExecStart: execStart}
	if v := os.Getenv("XDG_STATE_HOME"); filepath.IsAbs(v) {
		u.Env = map[string]string{"XDG_STATE_HOME": v}
	}
	return u
}

func UserUnitPath(home, name string) string {
	return filepath.Join(home, ".config", "systemd", "user", name+".service")
}

func (u UserUnit) Render() []byte {
	args := make([]string, len(u.ExecStart))
	for i, a := range u.ExecStart {
		args[i] = systemdQuote(a)
	}
	env := ""
	keys := make([]string, 0, len(u.Env))
	for k := range u.Env {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		env += "Environment=" + systemdQuote(k+"="+u.Env[k]) + "\n"
	}
	return []byte(fmt.Sprintf(`# Generated by %s install; edits are overwritten on the next install.
[Unit]
Description=%s
Documentation=https://github.com/tarakanof/Ember/blob/main/docs/RUNBOOK.md

[Service]
Type=simple
%sExecStart=%s
Restart=always
RestartSec=10
Nice=10
IOSchedulingClass=idle

[Install]
WantedBy=default.target
`, u.Name, systemdDescription(u.Description), env, strings.Join(args, " ")))
}

func systemdDescription(s string) string {
	s = strings.NewReplacer("\r", " ", "\n", " ").Replace(s)
	return strings.ReplaceAll(s, "%", "%%")
}

func systemdQuote(s string) string {
	s = strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		"\n", `\n`,
		"\r", `\r`,
		"%", "%%",
		"$", "$$",
	).Replace(s)
	return `"` + s + `"`
}

func systemctlUser(run Runner, args ...string) ([]byte, error) {
	return run("systemctl", append([]string{"--user"}, args...)...)
}

func InstallUserUnit(run Runner, home string, u UserUnit) error {
	path := UserUnitPath(home, u.Name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, u.Render(), 0o644); err != nil {
		return err
	}
	unit := u.Name + ".service"
	for _, args := range [][]string{{"daemon-reload"}, {"enable", unit}, {"restart", unit}} {
		if out, err := systemctlUser(run, args...); err != nil {
			return fmt.Errorf("systemctl --user %s: %v: %s\n"+
				"No user systemd session? Log in once (or run `loginctl enable-linger $USER`) and retry, "+
				"or run `%s` under your own supervisor",
				strings.Join(args, " "), err, strings.TrimSpace(string(out)), strings.Join(append([]string{filepath.Base(u.ExecStart[0])}, u.ExecStart[1:]...), " "))
		}
	}
	return nil
}

func UninstallUserUnit(run Runner, home, name string) error {
	path := UserUnitPath(home, name)
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return nil
	}
	_, _ = systemctlUser(run, "disable", "--now", name+".service")
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	_, _ = systemctlUser(run, "daemon-reload")
	return nil
}

func LingerHint(run Runner, user string) string {
	if user == "" {
		return ""
	}
	out, err := run("loginctl", "show-user", user, "--property=Linger")
	if err != nil || strings.TrimSpace(string(out)) == "Linger=yes" {
		return ""
	}
	return fmt.Sprintf("Note: lingering is off, so the unit stops when your last session ends. On a headless box run `sudo loginctl enable-linger %s`.", user)
}

func UserUnitStatus(run Runner, home, name, user string) []string {
	path := UserUnitPath(home, name)
	if _, err := os.Stat(path); err != nil {
		return []string{"systemd unit: NOT installed (run `install`)"}
	}
	unit := name + ".service"
	active, _ := systemctlUser(run, "is-active", unit)
	enabled, _ := systemctlUser(run, "is-enabled", unit)
	lines := []string{
		"systemd unit: installed at " + path,
		fmt.Sprintf("systemd unit: %s, %s (journal: journalctl --user -u %s)",
			dashIfBlank(string(active)), dashIfBlank(string(enabled)), unit),
	}
	if user != "" {
		out, err := run("loginctl", "show-user", user, "--property=Linger")
		linger := strings.TrimSpace(string(out))
		switch {
		case err != nil:
			lines = append(lines, "linger: unknown (loginctl failed)")
		case linger == "Linger=yes":
			lines = append(lines, "linger: Linger=yes (runs without a login session)")
		default:
			lines = append(lines, fmt.Sprintf("linger: %s — the unit stops when your last session ends; "+
				"on a headless box run `sudo loginctl enable-linger %s`", dashIfBlank(linger), user))
		}
	}
	return lines
}

func dashIfBlank(s string) string {
	if s = strings.TrimSpace(s); s == "" {
		return "-"
	}
	return s
}
