package producer

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// Runner runs a command and returns its combined output; tests fake it.
type Runner func(name string, args ...string) ([]byte, error)

// ExecRunner is the real Runner.
func ExecRunner(name string, args ...string) ([]byte, error) {
	return exec.Command(name, args...).CombinedOutput()
}

// UserUnit is a systemd --user service running a producer daemon: the Linux
// counterpart of the macOS LaunchAgent (KeepAlive -> Restart=always).
type UserUnit struct {
	Name        string   // unit name without ".service", e.g. "ember-codex-producer"
	Description string   // [Unit] Description
	ExecStart   []string // absolute binary path + args
}

// UserUnitPath is where the unit file lives (~/.config/systemd/user).
func UserUnitPath(home, name string) string {
	return filepath.Join(home, ".config", "systemd", "user", name+".service")
}

// Render returns the unit file body.
func (u UserUnit) Render() []byte {
	args := make([]string, len(u.ExecStart))
	for i, a := range u.ExecStart {
		args[i] = systemdQuote(a)
	}
	return []byte(fmt.Sprintf(`# Generated by %s install; edits are overwritten on the next install.
[Unit]
Description=%s
Documentation=https://github.com/tarakanof/Ember/blob/main/docs/RUNBOOK.md

[Service]
Type=simple
ExecStart=%s
Restart=always
RestartSec=10
Nice=10
IOSchedulingClass=idle

[Install]
WantedBy=default.target
`, u.Name, systemdEscape(u.Description), strings.Join(args, " ")))
}

func systemdEscape(s string) string {
	return strings.ReplaceAll(s, "%", "%%")
}

func systemdQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + systemdEscape(s) + `"`
}

func systemctlUser(run Runner, args ...string) ([]byte, error) {
	return run("systemctl", append([]string{"--user"}, args...)...)
}

// InstallUserUnit writes the unit, reloads the user manager, enables the unit
// and (re)starts it so a rebuilt binary takes over.
func InstallUserUnit(run Runner, home string, u UserUnit) error {
	path := UserUnitPath(home, u.Name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, u.Render(), 0o644); err != nil {
		return err
	}
	unit := u.Name + ".service"
	for _, args := range [][]string{{"daemon-reload"}, {"enable", unit}, {"restart", unit}} {
		if out, err := systemctlUser(run, args...); err != nil {
			return fmt.Errorf("systemctl --user %s: %v: %s\n"+
				"No user systemd session? Log in once (or run `loginctl enable-linger $USER`) and retry, "+
				"or run `%s` under your own supervisor",
				strings.Join(args, " "), err, strings.TrimSpace(string(out)), strings.Join(append([]string{filepath.Base(u.ExecStart[0])}, u.ExecStart[1:]...), " "))
		}
	}
	return nil
}

// UninstallUserUnit stops, disables and removes the unit; a missing unit is a no-op.
func UninstallUserUnit(run Runner, home, name string) error {
	path := UserUnitPath(home, name)
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return nil
	}
	_, _ = systemctlUser(run, "disable", "--now", name+".service")
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	_, _ = systemctlUser(run, "daemon-reload")
	return nil
}

// UserUnitStatus is doctor's view of the unit: installed, active/enabled, and
// whether lingering keeps it running without a login session.
func UserUnitStatus(run Runner, home, name, user string) []string {
	path := UserUnitPath(home, name)
	if _, err := os.Stat(path); err != nil {
		return []string{"systemd unit: NOT installed (run `install`)"}
	}
	unit := name + ".service"
	active, _ := systemctlUser(run, "is-active", unit)
	enabled, _ := systemctlUser(run, "is-enabled", unit)
	lines := []string{
		"systemd unit: installed at " + path,
		fmt.Sprintf("systemd unit: %s, %s (journal: journalctl --user -u %s)",
			dashIfBlank(string(active)), dashIfBlank(string(enabled)), unit),
	}
	if user != "" {
		out, err := run("loginctl", "show-user", user, "--property=Linger")
		linger := strings.TrimSpace(string(out))
		switch {
		case err != nil:
			lines = append(lines, "linger: unknown (loginctl failed)")
		case linger == "Linger=yes":
			lines = append(lines, "linger: Linger=yes (runs without a login session)")
		default:
			lines = append(lines, fmt.Sprintf("linger: %s — the unit stops when your last session ends; "+
				"on a headless box run `sudo loginctl enable-linger %s`", dashIfBlank(linger), user))
		}
	}
	return lines
}

func dashIfBlank(s string) string {
	if s = strings.TrimSpace(s); s == "" {
		return "-"
	}
	return s
}
