public enum SettingsKeys {
    public static let source = "EMBER_SOURCE"
    public static let serverURL = "EMBER_SERVER_URL"
    public static let token = "EMBER_TOKEN"
    public static let sourceColor = "EMBER_SOURCE_COLOR"
    public static let contextPct = "EMBER_CONTEXT_PCT_ENABLED"
    public static let activityDetail = "EMBER_ACTIVITY_DETAIL_ENABLED"
    public static let activityTrail = "EMBER_ACTIVITY_TRAIL_ENABLED"
    public static let rateBottomBar = "EMBER_RATE_BOTTOM_BAR"
    public static let sourceCard = "EMBER_SOURCE_CARD"
    public static let sessionBar = "EMBER_SESSION_BAR"
    public static let codexIncludeClaude = "EMBER_CODEX_INCLUDE_CLAUDE"
    public static let codexSources = "EMBER_CODEX_SOURCES"
    public static let codexAppServer = "EMBER_CODEX_APPSERVER"
    public static let doneTTLSeconds = "EMBER_DONE_TTL_SECONDS"
    public static let claudeAgentsPoll = "EMBER_CLAUDE_AGENTS_POLL"
    public static let statuslineTimeoutMs = "EMBER_STATUSLINE_TIMEOUT_MS"
}
